homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

# Tracker config
device_tracker:
  - platform: !secret tracker_platform
    host: !secret tracker_ip
    username: !secret tracker_username
    password: !secret tracker_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes
    port: !secret tracker_port

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:

# Weather Prediction
sensor:
  platform: yr
sensor ssl:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_command

sensor 2:
  platform: mqtt
  name: "Temperatur Bad"
  state_topic: !secret sensor_2_topic
  qos: 0
  unit_of_measurement: "ºC"
sensor 3:
  platform: mqtt
  name: "Fukt Bad"
  state_topic: !secret sensor_3_topic
  qos: 0
  unit_of_measurement: "%"
sensor 4:
  platform: mqtt
  name: "LUX Bad"
  state_topic: !secret sensor_4_topic
  qos: 0
  unit_of_measurement: "LUX"
sensor 5:
  platform: mqtt
  name: "Temperatur Stue"
  state_topic: !secret sensor_5_topic
  qos: 0
  unit_of_measurement: "ºC"
sensor 6:
  platform: mqtt
  name: "Fukt Stue"
  state_topic: !secret sensor_6_topic
  qos: 0
  unit_of_measurement: "%"
sensor 7:
  platform: mqtt
  name: "LUX Stue"
  state_topic: !secret sensor_7_topic
  qos: 0
  unit_of_measurement: "LUX"
sensor 8:
  platform: mqtt
  name: "Temperatur Balkong"
  state_topic: !secret sensor_8_topic
  qos: 0
  unit_of_measurement: "ºC"
sensor 9:
  platform: mqtt
  name: "Fukt Balkong"
  state_topic: !secret sensor_9_topic
  qos: 0
  unit_of_measurement: "%"
sensor 10:
  - platform: miflora
    mac: !secret sensor_10_mac
    name: Flower 1
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
binary_sensor:
  platform: mqtt
  name: "Motion Bad"
  state_topic: !secret binary_sensor_topic
  device_class: motion
#tradfri:
  host: !secret tradfri_ip
  api_key: !secret tradfri_apikey
light sonofftv:
  - platform: mqtt
    name: "Lys TV"
    state_topic: "stat/sonofflystv/POWER"
    command_topic: "cmnd/sonofflystv/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
switch sonoffswitch:
  - platform: mqtt
    name: "Bryter TV"
    state_topic: "stat/sonoffswitch/POWER"
    command_topic: "cmnd/sonoffswitch/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
light:
  - platform: mqtt_json
    name: "PixelRing Strip"
    state_topic: "sensor/neopixelring"
    command_topic: "sensor/neopixelring/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

input_slider:
  pixelring_animation_speed:
    name: PixelRing Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

# Configuration.yaml example
automation: !include automations.yaml

#automation: 
#  - alias: "PixelRing Animation Speed"
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: input_slider.pixelring_animation_speed
#    action:
#      - service: mqtt.publish
#        data_template:
#          topic: "sensor/neopixelring/set"
#          payload: '{"transition":{{ trigger.to_state.state | int }}}'
#sensor:
#  - platform: systemmonitor
#    resources:
#      - type: disk_use_percent
#        arg: /home
#      - type: memory_free

# Example configuration.yaml entry
media_player:
  - platform: webostv
    host: !secret webos_ip
    mac: !secret webos_mac
    name: LGwebOSTV
    filename: webostv.conf
    customize:
      sources:
        - livetv
        - youtube
        - makotv
        - netflix
        - DIGITALBOKS

scene:
  - name: turn_on_tv_lights
    entities:
      light.lys_tv: on
  - name: tv_lights_max
    entities:
      light.lys_tv: on

# Text to speech
tts:
  platform: google

group: !include groups.yaml
